version: '{build}'
clone_depth: 1

image:
- Visual Studio 2019
- Ubuntu

environment:
  ApiKey:
    secure: SeomICfFXAQobyK5uMGeAhb0uljBxicG4Z56pWxWCXA=
  SatelliteJobName: 'Image: Visual Studio 2019'
  FileName: 'libblosc2.dll'

branches:
  only:
  - master
  - dev

configuration:
  - Release

init:
  - ps: git config --global core.autocrlf true

install:
- ps: |
    if ($isLinux) 
    { 
      sudo apt-get update
    }

before_build:
- ps: dotnet --info
- ps: "Get-ChildItem Env:"
- ps: ./init_solution.ps1
- ps: Import-Module ./build/Start-ArtifactDownload.ps1 -Force
- ps: | 
    if ($isLinux) 
    { 
      New-Item -Force -ItemType directory -Path "./artifacts/download/bin32/"
      Start-ArtifactDownload -JobName $env:SatelliteJobName -SourceFileName "lib32" -TargetFilePath "./artifacts/download/bin32/$env:FileName" -ApiKey $env:ApiKey
      New-Item -Force -ItemType directory -Path "./artifacts/download/bin64/"
      Start-ArtifactDownload -JobName $env:SatelliteJobName -SourceFileName "lib64" -TargetFilePath "./artifacts/download/bin64/$env:FileName" -ApiKey $env:ApiKey 
    }

build_script:
- ps: |
    if ($isLinux) 
    { 
      make --directory "./artifacts/bin64"

      dotnet build ./src/Blosc2.PInvoke/Blosc2.PInvoke.csproj -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG /p:IsPublicBuild=True
    }
    elseif ($isWindows)
    { 
      msbuild ./artifacts/bin32/blosc/blosc2_shared.vcxproj /p:Configuration=$Env:CONFIGURATION
      msbuild ./artifacts/bin64/blosc/blosc2_shared.vcxproj /p:Configuration=$Env:CONFIGURATION

      dotnet build ./src/Blosc2.PInvoke/Blosc2.PInvoke.csproj -c $Env:CONFIGURATION /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG
    }

after_build:
- ps: |
    if ($isWindows) 
    { 
      Push-AppveyorArtifact "./artifacts/bin32/blosc/$Env:CONFIGURATION/$env:FileName" -FileName "lib32"
      Push-AppveyorArtifact "./artifacts/bin64/blosc/$Env:CONFIGURATION/$env:FileName" -FileName "lib64"
    }

test_script:
- ps: |
    dotnet test ./tests/Blosc2.PInvoke.Tests -c $Env:CONFIGURATION /p:BuildProjectReferences=false

after_test:
  - ps: if (-Not $isLinux) { Remove-Item ./artifacts/packages/*.nupkg }

artifacts:
  - path: ./artifacts/packages/**/*.nupkg

deploy:

# MyGet (dev)
  - provider: NuGet
    server: https://www.myget.org/F/apollo3zehn-dev/api/v2/package
    api_key:
      secure: DVadlPknnKPMR4F2+3VqeU7BFFmtLcXDHzkySA590MqQNIdzbx8HRuaPwDVbHRqX
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      branch: dev
      CI_LINUX: true

# NuGet (master)
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: vjCagztOaQ0GCHlolWbsRl/rh55NujGlT5fgW1Uo69DMA+8xt6NPKC56wRQ3s1Y7
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      CI_LINUX: true
      APPVEYOR_REPO_TAG: true
